repos:
  - repo: https://github.com/ambv/black
    rev: 21.5b1
    hooks:
    - id: black
  - repo:  https://github.com/pycqa/flake8
    rev: 3.9.1
    hooks:
    - id: flake8
      additional_dependencies:
        - flake8-bugbear
        - flake8-builtins
        - flake8-comprehensions
        - flake8-docstrings
        - flake8-rst-docstrings
        - pygments
      exclude: "^testsuite/tests/.*"
